# Generated by Django 2.2.4 on 2019-08-08 18:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/posts'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/posts'),
        ),
    ]
